apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi #minimalist
  storageClassName: standard